# Generated by Django 4.1.6 on 2023-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='account_id')),
                ('pw', models.CharField(max_length=10, verbose_name='pw')),
            ],
        ),
    ]
