# Generated by Django 4.1.6 on 2023-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='wiki_post_id',
            field=models.IntegerField(verbose_name='wiki_post_id'),
        ),
    ]
