# Generated by Django 4.1.6 on 2023-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_tags_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('account_id', models.IntegerField(verbose_name='account_id')),
                ('reputation', models.IntegerField(verbose_name='reputation')),
                ('views', models.IntegerField(verbose_name='views')),
                ('down_votes', models.IntegerField(default=0, verbose_name='down_votes')),
                ('up_votes', models.IntegerField(default=0, verbose_name='up_votes')),
                ('display_name', models.CharField(max_length=255, verbose_name='display_name')),
                ('location', models.CharField(max_length=512, verbose_name='location')),
                ('profile_image_url', models.CharField(max_length=255, verbose_name='profile_image_url')),
                ('website_url', models.CharField(max_length=255, verbose_name='website_url')),
                ('about_me', models.TextField(verbose_name='about_me')),
                ('creation_date', models.TimeField(verbose_name='creation_date')),
                ('last_access_date', models.TimeField(verbose_name='last_access_date')),
            ],
        ),
    ]
